<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
class Biodata_SiswaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('biodata_siswa')->insert([
            [
                'pengguna_id' => 4,
                'foto' => 'file_20240519034914.jpeg',
                'nama_lengkap' => 'Sakifa Gani',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir' => 'Tangerang',
                'tgl_lahir' => '2005-12-05',
                'agama' => 'Islam',
                'kewarganegaraan' => 'Indonesia',
                'alamat' => 'Jl. Benteng Betawi No. 9, Tangerang',
                'no_telepon' => '02112345678',
                'no_hp' => '08123456796',
                'pendidikan' => 'SMP',
                'diterimakursus' => '2022-02-01',
                'tingkat_kelas' => 'SMA',
                'nama_ortu' => 'Gani Ahmad',
                'tempat_lahir_ortu' => 'Tangerang',
                'tgl_lahir_ortu' => '1976-11-30',
                'agama_ortu' => 'Islam',
                'pendidikan_ortu' => 'S1',
                'pekerjaan_ortu' => 'Pengusaha'
            ],
            [
                'pengguna_id' => 5,
                'foto' => 'file_20240519034914.jpeg',
                'nama_lengkap' => 'Dani Sudirman',
                'jenis_kelamin' => 'Laki-laki',
                'tempat_lahir' => 'Bandung',
                'tgl_lahir' => '2005-04-10',
                'agama' => 'Islam',
                'kewarganegaraan' => 'Indonesia',
                'alamat' => 'Jl. Suka Maju No. 2, Bandung',
                'no_telepon' => '02212345678',
                'no_hp' => '08123456789',
                'pendidikan' => 'SMP',
                'diterimakursus' => '2021-07-01',
                'tingkat_kelas' => 'SMA',
                'nama_ortu' => 'Sudirman',
                'tempat_lahir_ortu' => 'Garut',
                'tgl_lahir_ortu' => '1970-05-15',
                'agama_ortu' => 'Islam',
                'pendidikan_ortu' => 'S1',
                'pekerjaan_ortu' => 'Guru'
            ],
            [
                'pengguna_id' => 6,
                'foto' => 'file_20240519034914.jpeg',
                'nama_lengkap' => 'Elsa Puspita',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir' => 'Surabaya',
                'tgl_lahir' => '2006-02-20',
                'agama' => 'Kristen',
                'kewarganegaraan' => 'Indonesia',
                'alamat' => 'Jl. Pemuda No. 3, Surabaya',
                'no_telepon' => '03112345678',
                'no_hp' => '08123456790',
                'pendidikan' => 'SMP',
                'diterimakursus' => '2021-08-01',
                'tingkat_kelas' => 'SMA',
                'nama_ortu' => 'Andi Puspita',
                'tempat_lahir_ortu' => 'Malang',
                'tgl_lahir_ortu' => '1975-06-25',
                'agama_ortu' => 'Kristen',
                'pendidikan_ortu' => 'S1',
                'pekerjaan_ortu' => 'Dokter'
            ],
            [
                'pengguna_id' => 7,
                'foto' => 'file_20240519034914.jpeg',
                'nama_lengkap' => 'Ramli Siregar',
                'jenis_kelamin' => 'Laki-laki',
                'tempat_lahir' => 'Medan',
                'tgl_lahir' => '2005-11-30',
                'agama' => 'Islam',
                'kewarganegaraan' => 'Indonesia',
                'alamat' => 'Jl. Sutomo No. 4, Medan',
                'no_telepon' => '06112345678',
                'no_hp' => '08123456791',
                'pendidikan' => 'SMP',
                'diterimakursus' => '2021-09-01',
                'tingkat_kelas' => 'SMA',
                'nama_ortu' => 'Zainal Siregar',
                'tempat_lahir_ortu' => 'Padang',
                'tgl_lahir_ortu' => '1973-04-10',
                'agama_ortu' => 'Islam',
                'pendidikan_ortu' => 'S1',
                'pekerjaan_ortu' => 'Wiraswasta'
            ],
            [
                'pengguna_id' => 8,
                'foto' => 'file_20240519034914.jpeg',
                'nama_lengkap' => 'Joko Santoso',
                'jenis_kelamin' => 'Laki-laki',
                'tempat_lahir' => 'Yogyakarta',
                'tgl_lahir' => '2006-01-25',
                'agama' => 'Katolik',
                'kewarganegaraan' => 'Indonesia',
                'alamat' => 'Jl. Malioboro No. 5, Yogyakarta',
                'no_telepon' => '027412345678',
                'no_hp' => '08123456792',
                'pendidikan' => 'SMP',
                'diterimakursus' => '2021-10-01',
                'tingkat_kelas' => 'SMA',
                'nama_ortu' => 'Slamet Santoso',
                'tempat_lahir_ortu' => 'Solo',
                'tgl_lahir_ortu' => '1978-07-15',
                'agama_ortu' => 'Katolik',
                'pendidikan_ortu' => 'S1',
                'pekerjaan_ortu' => 'Pegawai Swasta'
            ],
            [
                'pengguna_id' => 9,
                'foto' => 'file_20240519034914.jpeg',
                'nama_lengkap' => 'Rahma Dewi',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir' => 'Makassar',
                'tgl_lahir' => '2005-07-10',
                'agama' => 'Islam',
                'kewarganegaraan' => 'Indonesia',
                'alamat' => 'Jl. Pattimura No. 6, Makassar',
                'no_telepon' => '041112345678',
                'no_hp' => '08123456793',
                'pendidikan' => 'SMP',
                'diterimakursus' => '2021-11-01',
                'tingkat_kelas' => 'SMA',
                'nama_ortu' => 'Amiruddin',
                'tempat_lahir_ortu' => 'Bone',
                'tgl_lahir_ortu' => '1972-03-05',
                'agama_ortu' => 'Islam',
                'pendidikan_ortu' => 'S1',
                'pekerjaan_ortu' => 'Pedagang'
            ],
            [
                'pengguna_id' => 10,
                'foto' => 'file_20240519034914.jpeg',
                'nama_lengkap' => 'Ani Marlina',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir' => 'Palembang',
                'tgl_lahir' => '2005-09-15',
                'agama' => 'Islam',
                'kewarganegaraan' => 'Indonesia',
                'alamat' => 'Jl. Demang Lebar Daun No. 7, Palembang',
                'no_telepon' => '071112345678',
                'no_hp' => '08123456794',
                'pendidikan' => 'SMP',
                'diterimakursus' => '2021-12-01',
                'tingkat_kelas' => 'SMA',
                'nama_ortu' => 'Marlina',
                'tempat_lahir_ortu' => 'Palembang',
                'tgl_lahir_ortu' => '1975-12-20',
                'agama_ortu' => 'Islam',
                'pendidikan_ortu' => 'S1',
                'pekerjaan_ortu' => 'Ibu Rumah Tangga'
            ],
            [
                'pengguna_id' => 11,
                'foto' => 'file_20240519034914.jpeg',
                'nama_lengkap' => 'Budi Santoso',
                'jenis_kelamin' => 'Laki-laki',
                'tempat_lahir' => 'Semarang',
                'tgl_lahir' => '2006-05-25',
                'agama' => 'Hindu',
                'kewarganegaraan' => 'Indonesia',
                'alamat' => 'Jl. Diponegoro No. 8, Semarang',
                'no_telepon' => '02412345678',
                'no_hp' => '08123456795',
                'pendidikan' => 'SMP',
                'diterimakursus' => '2022-01-01',
                'tingkat_kelas' => 'SMA',
                'nama_ortu' => 'Santoso',
                'tempat_lahir_ortu' => 'Magelang',
                'tgl_lahir_ortu' => '1974-08-10',
                'agama_ortu' => 'Hindu',
                'pendidikan_ortu' => 'S1',
                'pekerjaan_ortu' => 'Pegawai Negeri'
            ]
    ]);
    }
    
}
